### ISSUE TITLE
Please consider adding a LICENSE to this repository.

### ISSUE THREAD

**Issue by floatingatoll** [swathiiyer2/fathom-webextension#2]
Through a chain of forks, this repository was recently forked by someone into the Mozilla organization. As part of ensuring that we have a clean chain of ownership, I request that you apply a LICENSE to this repository (MPL2 is typically appropriate, unless external constraints warrant otherwise) so that we can import that LICENSE through the chain of forks into our forked repository.

**Comment by swathiiyer2** [comment]
Sure, I have merged the last branch with the license.

**Comment by floatingatoll** [comment]
Thank you! Really appreciate it.
